vich_uploader:
   db_driver: orm

   metadata:
      type: attribute
     
   mappings:
      services:
         uri_prefix: /uploads/services
         upload_destination: '%kernel.project_dir%/public/uploads/services'
         namer: Vich\UploaderBundle\Naming\UniqidNamer
      
      teams:
         uri_prefix: /uploads/teams
         upload_destination: '%kernel.project_dir%/public/uploads/teams'
         namer: Vich\UploaderBundle\Naming\UniqidNamer

      blogs:
         uri_prefix: /uploads/blogs
         upload_destination: '%kernel.project_dir%/public/uploads/blogs'
         namer: Vich\UploaderBundle\Naming\UniqidNamer

   #mappings:
   #    products:
   #        uri_prefix: /images/products
   #        upload_destination: '%kernel.project_dir%/public/images/products'
